export const GET_REQUEST_CLEANING_TOOL_HISTORY =
  "GET_REQUEST_CLEANING_TOOL_HISTORY";
export const GET_REQUEST_CLEANING_TOOL_HISTORY_SUCCESS =
  "GET_REQUEST_CLEANING_TOOL_HISTORY_SUCCESS";
export const GET_REQUEST_CLEANING_TOOL_HISTORY_FAILED =
  "GET_REQUEST_CLEANING_TOOL_HISTORY_FAILED";
