export const GET_REQUEST_CLEANING_TOOL_APPROVED =
  "GET_REQUEST_CLEANING_TOOL_APPROVED";
export const GET_REQUEST_CLEANING_TOOL_APPROVED_SUCCESS =
  "GET_REQUEST_CLEANING_TOOL_APPROVED_SUCCESS";
export const GET_REQUEST_CLEANING_TOOL_APPROVED_FAILED =
  "GET_REQUEST_CLEANING_TOOL_APPROVED_FAILED";
