export const GET_REQUEST_CLEANING_TOOL_PENDING =
  "GET_REQUEST_CLEANING_TOOL_PENDING";
export const GET_REQUEST_CLEANING_TOOL_PENDING_SUCCESS =
  "GET_REQUEST_CLEANING_TOOL_PENDING_SUCCESS";
export const GET_REQUEST_CLEANING_TOOL_PENDING_FAILED =
  "GET_REQUEST_CLEANING_TOOL_PENDING_FAILED";
