export const GET_TRANSACTION_USER = "GET_TRANSACTION_USER";
export const GET_TRANSACTION_USER_SUCCESS = "GET_TRANSACTION_USER_SUCCESS";
export const GET_TRANSACTION_USER_FAILED = "GET_TRANSACTION_USER_FAILED";
