export const GET_TRANSACTION_COMPANY = "GET_TRANSACTION_COMPANY";
export const GET_TRANSACTION_COMPANY_SUCCESS =
  "GET_TRANSACTION_COMPANY_SUCCESS";
export const GET_TRANSACTION_COMPANY_FAILED = "GET_TRANSACTION_COMPANY_FAILED";
