export const GET_NEW_BOOKING_DETAIL = "GET_NEW_BOOKING_DETAIL";
export const GET_NEW_BOOKING_DETAIL_SUCCESS = "GET_NEW_BOOKING_DETAIL_SUCCESS";
export const GET_NEW_BOOKING_DETAIL_FAILED = "GET_NEW_BOOKING_DETAIL_FAILED";
