export const SEARCH_BOOKING_IN_WORKING = "SEARCH_BOOKING_IN_WORKING";
export const SEARCH_BOOKING_IN_WORKING_SUCCESS =
  "SEARCH_BOOKING_IN_WORKING_SUCCESS";
export const SEARCH_BOOKING_IN_WORKING_FAILED =
  "SEARCH_BOOKING_IN_WORKING_FAILED";
