export const SEARCH_CLEANING_TOOL = "SEARCH_CLEANING_TOOL";
export const SEARCH_CLEANING_TOOL_SUCCESS = "SEARCH_CLEANING_TOOL_SUCCESS";
export const SEARCH_CLEANING_TOOL_FAILED = "SEARCH_CLEANING_TOOL_FAILED";
