export const GET_EMPLOYEES_BY_ID = "GET_EMPLOYEES_BY_ID";
export const GET_EMPLOYEES_BY_ID_SUCCESS = "GET_EMPLOYEES_BY_ID_SUCCESS";
export const GET_EMPLOYEES_BY_ID_FAILED = "GET_EMPLOYEES_BY_ID_FAILED";
