export const GET_WARDS_AND_DISTRICS2 = "GET_WARDS_AND_DISTRICS2";
export const GET_WARDS_AND_DISTRICS_SUCCESS2 =
  "GET_WARDS_AND_DISTRICS_SUCCESS2";
export const GET_WARDS_AND_DISTRICS_FAILED2 = "GET_WARDS_AND_DISTRICS_FAILED2";
