export const GET_WARDS_AND_DISTRICS = "GET_WARDS_AND_DISTRICS";
export const GET_WARDS_AND_DISTRICS_SUCCESS = "GET_WARDS_AND_DISTRICS_SUCCESS";
export const GET_WARDS_AND_DISTRICS_FAILED = "GET_WARDS_AND_DISTRICS_FAILED";
