export const SEARCH_SERVICE_GROUP = "SEARCH_SERVICE_GROUP";
export const SEARCH_SERVICE_GROUP_SUCCESS = "SEARCH_SERVICE_GROUP_SUCCESS";
export const SEARCH_SERVICE_GROUP_FAILED = "SEARCH_SERVICE_GROUP_FAILED";
